# Makefile generated by BNFC, modified manually.

GHC		= ghc
GHC_OPTS = -o bin/Compiler
GHC_TOPTS = -o bin/Test
HAPPY	  = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX	   = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Gramma/Abs.hs Gramma/Layout.hs Gramma/Lex.hs \
	Gramma/Par.hs Gramma/Print.hs Gramma/Doc.txt \
	Gramma/Par.info MyFuns bin/Compiler bin/Test  \
	clean

# Rules for building the parser.

Gramma/Test.hs Gramma/Skel.hs Gramma/Abs.hs Gramma/Layout.hs Gramma/Lex.xGramma/Par.y Gramma/Print.hs Gramma/Doc.txt : Gramma.cf
	bnfc --haskell -d --text-token Gramma.cf
	rm Gramma/ErrM.hs

Gramma/Par.info : Gramma/Lex.hs Gramma/Par.hs

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Gramma/Test : Gramma/Abs.hs Gramma/Layout.hs grammar/Gramma/Lex.hs Gramma/Par.hs Gramma/Print.hs Gramma/Test.hs
	${GHC}  $@

MyFuns/Flow.hs : MyFuns/Flow.hs
	${GHC}  $@

bin/Compiler : Main.hs
	${GHC} ${GHC_OPTS} $<

bin/Test : Gramma/Test.hs
	${GHC} ${GHC_TOPTS} $<

# Rules for cleaning generated files.

clean :
	-rm -f Gramma/*.bak
	find . -name "*.o" -exec rm {} +
	find . -name "*.hi" -exec rm {} +

distclean : clean
	-rm -f Gramma/Abs.hs Gramma/Doc.txt Gramma/ErrM.hs Gramma/Layout.hs Gramma/Lex.x Gramma/Par.y Gramma/Print.hs Gramma/Skel.hs Gramma/Test.hs Gramma/Lex.hs Gramma/Par.hs Gramma/Par.info
